# Auto-generated by generate_schemas.py
from __future__ import annotations
from typing import Optional, Any
from datetime import date, datetime, time
from decimal import Decimal
from uuid import UUID
from pydantic import BaseModel, ConfigDict

class EvForecastStatsCreate(BaseModel):
    hour: int
    mean_energy_kwh: float
    std_energy_kwh: float
    mean_duration_hours: float
    std_duration_hours: float
    sample_count: int
    updated_at: datetime
    id_charger: Optional[UUID] = None

class EvForecastStatsUpdate(BaseModel):
    id: Optional[UUID] = None
    hour: Optional[int] = None
    mean_energy_kwh: Optional[float] = None
    std_energy_kwh: Optional[float] = None
    mean_duration_hours: Optional[float] = None
    std_duration_hours: Optional[float] = None
    sample_count: Optional[int] = None
    updated_at: Optional[datetime] = None
    id_charger: Optional[UUID] = None

class EvForecastStatsRead(BaseModel):
    id: UUID
    hour: int
    mean_energy_kwh: float
    std_energy_kwh: float
    mean_duration_hours: float
    std_duration_hours: float
    sample_count: int
    updated_at: datetime
    id_charger: Optional[UUID]
    model_config = ConfigDict(from_attributes=True)

class ChargersCreate(BaseModel):
    name: str
    type: str
    latitude: float
    longitude: float
    nominal_power: float
    plugs: str
    updated_at: datetime
    id_owner: Optional[UUID] = None

class ChargersUpdate(BaseModel):
    id: Optional[UUID] = None
    name: Optional[str] = None
    type: Optional[str] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    nominal_power: Optional[float] = None
    plugs: Optional[str] = None
    updated_at: Optional[datetime] = None
    id_owner: Optional[UUID] = None

class ChargersRead(BaseModel):
    id: UUID
    name: str
    type: str
    latitude: float
    longitude: float
    nominal_power: float
    plugs: str
    updated_at: datetime
    id_owner: Optional[UUID]
    model_config = ConfigDict(from_attributes=True)

class GridLoadForecastedCreate(BaseModel):
    value: float
    id_action: Optional[UUID] = None

class GridLoadForecastedUpdate(BaseModel):
    id: Optional[UUID] = None
    value: Optional[float] = None
    id_action: Optional[UUID] = None

class GridLoadForecastedRead(BaseModel):
    id: UUID
    value: float
    id_action: Optional[UUID]
    model_config = ConfigDict(from_attributes=True)

class ChargingSessionsCreate(BaseModel):
    start_time: datetime
    energy_delivered_kwh: float
    forecasted_energy_kwh: float
    forecasted_energy_kwh_std: float
    forecasted_duration_hours: float
    forecasted_duration_hours_std: float
    controlled_charging_points: int
    active: bool
    updated_at: datetime
    id_charger: Optional[UUID] = None
    end_time: Optional[datetime] = None
    end_charging_time: Optional[datetime] = None
    duration: Optional[float] = None

class ChargingSessionsUpdate(BaseModel):
    id: Optional[UUID] = None
    start_time: Optional[datetime] = None
    energy_delivered_kwh: Optional[float] = None
    forecasted_energy_kwh: Optional[float] = None
    forecasted_energy_kwh_std: Optional[float] = None
    forecasted_duration_hours: Optional[float] = None
    forecasted_duration_hours_std: Optional[float] = None
    controlled_charging_points: Optional[int] = None
    active: Optional[bool] = None
    updated_at: Optional[datetime] = None
    id_charger: Optional[UUID] = None
    end_time: Optional[datetime] = None
    end_charging_time: Optional[datetime] = None
    duration: Optional[float] = None

class ChargingSessionsRead(BaseModel):
    id: UUID
    start_time: datetime
    energy_delivered_kwh: float
    forecasted_energy_kwh: float
    forecasted_energy_kwh_std: float
    forecasted_duration_hours: float
    forecasted_duration_hours_std: float
    controlled_charging_points: int
    active: bool
    updated_at: datetime
    id_charger: Optional[UUID]
    end_time: Optional[datetime]
    end_charging_time: Optional[datetime]
    duration: Optional[float]
    model_config = ConfigDict(from_attributes=True)

class EvDurationCdfCreate(BaseModel):
    hour: int
    horizon_hours: float
    probability: float
    sample_count: int
    updated_at: datetime
    id_charger: Optional[UUID] = None

class EvDurationCdfUpdate(BaseModel):
    id: Optional[UUID] = None
    hour: Optional[int] = None
    horizon_hours: Optional[float] = None
    probability: Optional[float] = None
    sample_count: Optional[int] = None
    updated_at: Optional[datetime] = None
    id_charger: Optional[UUID] = None

class EvDurationCdfRead(BaseModel):
    id: UUID
    hour: int
    horizon_hours: float
    probability: float
    sample_count: int
    updated_at: datetime
    id_charger: Optional[UUID]
    model_config = ConfigDict(from_attributes=True)

class OwnersCreate(BaseModel):
    user: str
    password: str
    company_name: str
    updated_at: datetime

class OwnersUpdate(BaseModel):
    id: Optional[UUID] = None
    user: Optional[str] = None
    password: Optional[str] = None
    company_name: Optional[str] = None
    updated_at: Optional[datetime] = None

class OwnersRead(BaseModel):
    id: UUID
    user: str
    password: str
    company_name: str
    updated_at: datetime
    model_config = ConfigDict(from_attributes=True)

class ActionsCreate(BaseModel):
    current_time: datetime
    current_power_kw: float
    energy_delivered_kwh: float
    is_fully_charged: bool
    probability_disconnection: float
    cumulative_duration_probability: float
    action: str
    id_cs: Optional[UUID] = None

class ActionsUpdate(BaseModel):
    id: Optional[UUID] = None
    current_time: Optional[datetime] = None
    current_power_kw: Optional[float] = None
    energy_delivered_kwh: Optional[float] = None
    is_fully_charged: Optional[bool] = None
    probability_disconnection: Optional[float] = None
    cumulative_duration_probability: Optional[float] = None
    action: Optional[str] = None
    id_cs: Optional[UUID] = None

class ActionsRead(BaseModel):
    id: UUID
    current_time: datetime
    current_power_kw: float
    energy_delivered_kwh: float
    is_fully_charged: bool
    probability_disconnection: float
    cumulative_duration_probability: float
    action: str
    id_cs: Optional[UUID]
    model_config = ConfigDict(from_attributes=True)
