# Auto-generated by generate_schemas.py
from __future__ import annotations
from typing import Optional, Any
from datetime import date, datetime, time
from decimal import Decimal
from uuid import UUID
from pydantic import BaseModel, ConfigDict

class ChargersCreate(BaseModel):
    name: str
    type: str
    latitude: float
    longitude: float
    nominal_power: float
    plugs: str
    id_owner: Optional[UUID] = None
    id_pilot: Optional[UUID] = None
    control_algorithm: Optional[str] = None
    control_policy: Optional[str] = None

class ChargersUpdate(BaseModel):
    id: Optional[UUID] = None
    name: Optional[str] = None
    type: Optional[str] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    nominal_power: Optional[float] = None
    plugs: Optional[str] = None
    updated_at: Optional[datetime] = None
    id_owner: Optional[UUID] = None
    id_pilot: Optional[UUID] = None
    control_algorithm: Optional[str] = None
    control_policy: Optional[str] = None

class ChargersRead(BaseModel):
    id: UUID
    name: str
    type: str
    latitude: float
    longitude: float
    nominal_power: float
    plugs: str
    updated_at: datetime
    id_owner: Optional[UUID]
    id_pilot: Optional[UUID]
    control_algorithm: Optional[str] = None
    control_policy: Optional[str] = None
    model_config = ConfigDict(from_attributes=True)

class ChargingSessionsCreate(BaseModel):
    start_time: datetime
    energy_delivered_kwh: float
    forecasted_energy_kwh: float
    forecasted_energy_kwh_std: float
    forecasted_duration_hours: float
    forecasted_duration_hours_std: float
    controlled_charging_points: int
    active: bool
    id_charger: Optional[UUID] = None
    end_time: Optional[datetime] = None
    end_charging_time: Optional[datetime] = None
    duration: Optional[float] = None
    last_event_time: Optional[datetime] = None

class ChargingSessionsUpdate(BaseModel):
    id: Optional[UUID] = None
    start_time: Optional[datetime] = None
    energy_delivered_kwh: Optional[float] = None
    forecasted_energy_kwh: Optional[float] = None
    forecasted_energy_kwh_std: Optional[float] = None
    forecasted_duration_hours: Optional[float] = None
    forecasted_duration_hours_std: Optional[float] = None
    controlled_charging_points: Optional[int] = None
    active: Optional[bool] = None
    updated_at: Optional[datetime] = None
    id_charger: Optional[UUID] = None
    end_time: Optional[datetime] = None
    end_charging_time: Optional[datetime] = None
    duration: Optional[float] = None
    last_event_time: Optional[datetime] = None

class ChargingSessionsRead(BaseModel):
    id: UUID
    start_time: datetime
    energy_delivered_kwh: float
    forecasted_energy_kwh: float
    forecasted_energy_kwh_std: float
    forecasted_duration_hours: float
    forecasted_duration_hours_std: float
    controlled_charging_points: int
    active: bool
    updated_at: datetime
    id_charger: Optional[UUID]
    end_time: Optional[datetime]
    end_charging_time: Optional[datetime]
    duration: Optional[float]
    last_event_time: Optional[datetime] = None
    model_config = ConfigDict(from_attributes=True)

class GridLoadForecastedCreate(BaseModel):
    value: float
    forecast_timestamp: datetime
    id_action: Optional[UUID] = None

class GridLoadForecastedUpdate(BaseModel):
    id: Optional[UUID] = None
    value: Optional[float] = None
    forecast_timestamp: Optional[datetime] = None
    id_action: Optional[UUID] = None

class GridLoadForecastedRead(BaseModel):
    id: UUID
    value: float
    forecast_timestamp: datetime
    id_action: Optional[UUID]
    model_config = ConfigDict(from_attributes=True)

class OwnersCreate(BaseModel):
    user: str
    password: str
    company_name: str
    type: Optional[str] = None
    role: Optional[str] = None

class OwnersUpdate(BaseModel):
    id: Optional[UUID] = None
    user: Optional[str] = None
    password: Optional[str] = None
    company_name: Optional[str] = None
    updated_at: Optional[datetime] = None
    type: Optional[str] = None
    role: Optional[str] = None

class OwnersRead(BaseModel):
    id: UUID
    user: str
    password: str
    company_name: str
    updated_at: datetime
    type: Optional[str]
    role: Optional[str]
    model_config = ConfigDict(from_attributes=True)

class EvDurationCdfCreate(BaseModel):
    local_hour: int
    horizon_hours: float
    probability: float
    sample_count: int
    id_charger: Optional[UUID] = None

class EvDurationCdfUpdate(BaseModel):
    id: Optional[UUID] = None
    local_hour: Optional[int] = None
    horizon_hours: Optional[float] = None
    probability: Optional[float] = None
    sample_count: Optional[int] = None
    updated_at: Optional[datetime] = None
    id_charger: Optional[UUID] = None

class EvDurationCdfRead(BaseModel):
    id: UUID
    local_hour: int
    horizon_hours: float
    probability: float
    sample_count: int
    updated_at: datetime
    id_charger: Optional[UUID]
    model_config = ConfigDict(from_attributes=True)

class PilotCreate(BaseModel):
    name: str
    id_owner: UUID
    timezone_name: str = "Europe/Zurich"
    forecast_meter: Optional[str] = None
    forecast_site: Optional[str] = None
    policy_signals: Optional[dict[str, Any]] = None

class PilotUpdate(BaseModel):
    id: Optional[UUID] = None
    name: Optional[str] = None
    id_owner: Optional[UUID] = None
    timezone_name: Optional[str] = None
    forecast_meter: Optional[str] = None
    forecast_site: Optional[str] = None
    policy_signals: Optional[dict[str, Any]] = None

class PilotRead(BaseModel):
    id: UUID
    name: str
    id_owner: UUID
    timezone_name: str
    forecast_meter: Optional[str]
    forecast_site: Optional[str]
    policy_signals: Optional[dict[str, Any]] = None
    model_config = ConfigDict(from_attributes=True)

class EvForecastStatsCreate(BaseModel):
    local_hour: int
    mean_energy_kwh: float
    std_energy_kwh: float
    mean_duration_hours: float
    std_duration_hours: float
    sample_count: int
    id_charger: Optional[UUID] = None

class EvForecastStatsUpdate(BaseModel):
    id: Optional[UUID] = None
    local_hour: Optional[int] = None
    mean_energy_kwh: Optional[float] = None
    std_energy_kwh: Optional[float] = None
    mean_duration_hours: Optional[float] = None
    std_duration_hours: Optional[float] = None
    sample_count: Optional[int] = None
    updated_at: Optional[datetime] = None
    id_charger: Optional[UUID] = None

class EvForecastStatsRead(BaseModel):
    id: UUID
    local_hour: int
    mean_energy_kwh: float
    std_energy_kwh: float
    mean_duration_hours: float
    std_duration_hours: float
    sample_count: int
    updated_at: datetime
    id_charger: Optional[UUID]
    model_config = ConfigDict(from_attributes=True)

class ActionsCreate(BaseModel):
    current_time: datetime
    current_power_kw: float
    energy_delivered_kwh: float
    is_fully_charged: bool
    probability_disconnection: float
    cumulative_duration_probability: float
    suggested_action: Optional[str] = None
    id_cs: Optional[UUID] = None
    control_policy: Optional[str] = None
    control_algorithm: Optional[str] = None
    correction_applied: bool = False
    suggested_power_kw: Optional[float] = None
    real_action: Optional[str] = None
    real_power_kw: Optional[float] = None
    decision_context: Optional[dict[str, Any]] = None
    policy_error: bool = False
    policy_error_message: Optional[str] = None

class ActionsUpdate(BaseModel):
    id: Optional[UUID] = None
    current_time: Optional[datetime] = None
    current_power_kw: Optional[float] = None
    energy_delivered_kwh: Optional[float] = None
    is_fully_charged: Optional[bool] = None
    probability_disconnection: Optional[float] = None
    cumulative_duration_probability: Optional[float] = None
    suggested_action: Optional[str] = None
    id_cs: Optional[UUID] = None
    control_policy: Optional[str] = None
    control_algorithm: Optional[str] = None
    correction_applied: Optional[bool] = None
    suggested_power_kw: Optional[float] = None
    real_action: Optional[str] = None
    real_power_kw: Optional[float] = None
    decision_context: Optional[dict[str, Any]] = None
    policy_error: Optional[bool] = None
    policy_error_message: Optional[str] = None

class ActionsRead(BaseModel):
    id: UUID
    current_time: datetime
    current_power_kw: float
    energy_delivered_kwh: float
    is_fully_charged: bool
    probability_disconnection: float
    cumulative_duration_probability: float
    suggested_action: Optional[str] = None
    id_cs: Optional[UUID]
    control_policy: Optional[str] = None
    control_algorithm: Optional[str] = None
    correction_applied: bool = False
    suggested_power_kw: Optional[float] = None
    real_action: Optional[str] = None
    real_power_kw: Optional[float] = None
    decision_context: Optional[dict[str, Any]] = None
    policy_error: bool = False
    policy_error_message: Optional[str] = None
    model_config = ConfigDict(from_attributes=True)


class SystemErrorsRead(BaseModel):
    id: UUID
    occurred_at: datetime
    source: str
    charger_id: Optional[UUID] = None
    session_id: Optional[UUID] = None
    error_message: str
    context: Optional[dict[str, Any]] = None
    model_config = ConfigDict(from_attributes=True)


class EvPilotForecastTimeseriesRead(BaseModel):
    id: UUID
    id_pilot: UUID
    run_at: datetime
    origin_time: datetime
    forecast_time: datetime
    presence: float
    energy_kwh: float
    artifact_name: str
    quantiles_json: Optional[dict[str, Any]] = None
    model_config = ConfigDict(from_attributes=True)


class ForecastJobCreate(BaseModel):
    job_id: str
    id_pilot: UUID
    enabled: bool = False
    predict_periodicity_minutes: int = 15
    artifact_path: str
    kind: str = "reg"
    freq: str = "15min"
    timezone: str = "UTC"
    horizon: Optional[int] = None
    sim_steps: int = 24
    sim_dt_hours: float = 1.0
    sim_power_kw: float = 11.0
    cal_fraction: float = 0.2
    lags: Optional[list[int]] = None


class ForecastJobUpdate(BaseModel):
    job_id: Optional[str] = None
    enabled: Optional[bool] = None
    predict_periodicity_minutes: Optional[int] = None
    artifact_path: Optional[str] = None
    kind: Optional[str] = None
    freq: Optional[str] = None
    timezone: Optional[str] = None
    horizon: Optional[int] = None
    sim_steps: Optional[int] = None
    sim_dt_hours: Optional[float] = None
    sim_power_kw: Optional[float] = None
    cal_fraction: Optional[float] = None
    lags: Optional[list[int]] = None


class ForecastJobRead(BaseModel):
    id: UUID
    job_id: str
    id_pilot: UUID
    enabled: bool
    predict_periodicity_minutes: int
    artifact_path: str
    kind: str
    freq: str
    timezone: str
    horizon: Optional[int]
    sim_steps: int
    sim_dt_hours: float
    sim_power_kw: float
    cal_fraction: float
    lags: Optional[list[int]]
    updated_at: datetime
    model_config = ConfigDict(from_attributes=True)
