#!/usr/bin/env python3
"""
Run an end-to-end API test for the deployed EV Orchestrator service.

Run directly in PyCharm or with:
    python run_e2e_api_test.py

Before running, edit the ADMIN_USERNAME and ADMIN_PASSWORD constants below.
No environment variables or command-line arguments are required.

Expected workflow:
    1. Run generate_charging_schedule.py once.
    2. Edit ADMIN_USERNAME / ADMIN_PASSWORD in this file.
    3. Run this file.
"""

from __future__ import annotations

import csv
import json
import logging
import math
import random
import sys
import time
from collections import defaultdict
from dataclasses import asdict, dataclass
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Iterable
from zoneinfo import ZoneInfo

import requests

# =============================================================================
# EDITABLE CONFIGURATION — NO ENVIRONMENT VARIABLES ARE USED
# =============================================================================

# For a local test, set BASE_URL = "http://localhost:8000" (or wherever the
# service is running) and keep SCHEDULE_DAYS = 1. For the partner deployment,
# use the production URL and SCHEDULE_DAYS = 7.
BASE_URL = "https://example.com/ev-orchestrator"
# BASE_URL = "http://localhost:8000"
TIMEZONE = "Europe/Zurich"

# Replace these two placeholders locally before running the API test.
ADMIN_USERNAME = "first_admin"
ADMIN_PASSWORD = "REDACTED"
# ADMIN_USERNAME = "supsi_admin"
# ADMIN_PASSWORD = "replace-with-initial-admin-password"

TEST_USERNAME = "interped_user1"
TEST_PASSWORD = "REDACTED"
TEST_USER_TYPE = "user-adv" #it doesnt influence the authorization permitssions 
TEST_USER_ROLE = "user"
TEST_COMPANY_NAME = "InterPED Synthetic Test User"

PILOT_NAME = "interped_example pilot"
PILOT_TIMEZONE = "Europe/Zurich"

CHARGER_COUNT = 5
CHARGER_TYPE = "V1G"
NOMINAL_POWER_KW = 11.0
PLUGS = "Type2"

# Swiss coordinates around Lugano/Ticino. Each charger gets a small offset.
BASE_LATITUDE = 46.0037
BASE_LONGITUDE = 8.9511

SCRIPT_DIR = Path(__file__).resolve().parent
OUTPUT_DIR = SCRIPT_DIR / "outputs"
SCHEDULE_CSV_PATH = OUTPUT_DIR / "synthetic_charging_schedule.csv"

# Generated by this runner.
RUN_LOG_PREFIX = "ev_orchestrator_e2e"
RESOLVED_SCHEDULE_PREFIX = "synthetic_charging_schedule_resolved"

# Schedule execution settings.
# TIME_SCALE = 1      -> 7 simulated days take 7 real days.
# TIME_SCALE = 1440   -> 1 simulated day takes 1 real minute; 7 days take about 7 minutes.
TIME_SCALE = 1
USE_SLEEP_BETWEEN_SCHEDULED_CALLS = True
START_DELAY_MINUTES = 1
ACTIVE_SESSION_CHECKS_PER_DAY = 4
# Keep SCHEDULE_DAYS in sync with the value used in generate_charging_schedule.py.
SCHEDULE_DAYS = 3

# HTTP and validation settings.
HTTP_TIMEOUT_SECONDS = 30.0
FORECAST_COMPARISON_ABS_TOLERANCE = 1e-6
RANDOM_SEED = 20260610

# If True, the script stops after setup and CSV resolution, without sending session events.
DRY_RUN_AFTER_SETUP = False


# =============================================================================
# LOGGING
# =============================================================================

def now_utc_iso() -> str:
    return datetime.utcnow().replace(microsecond=0).isoformat() + "Z"


def redact(value: Any) -> Any:
    sensitive_keys = {"password", "token", "access_token", "authorization"}
    if isinstance(value, dict):
        return {k: "***REDACTED***" if str(k).lower() in sensitive_keys else redact(v) for k, v in value.items()}
    if isinstance(value, list):
        return [redact(v) for v in value]
    if isinstance(value, tuple):
        return tuple(redact(v) for v in value)
    if isinstance(value, datetime):
        return value.isoformat()
    return value


class StructuredLogger:
    def __init__(self, output_dir: Path, run_id: str):
        output_dir.mkdir(parents=True, exist_ok=True)
        self.human_log_path = output_dir / f"{RUN_LOG_PREFIX}_{run_id}.log"
        self.jsonl_log_path = output_dir / f"{RUN_LOG_PREFIX}_{run_id}.jsonl"

        self.logger = logging.getLogger(f"{RUN_LOG_PREFIX}_{run_id}")
        self.logger.setLevel(logging.INFO)
        self.logger.handlers.clear()

        fmt = logging.Formatter("%(asctime)s | %(levelname)s | %(message)s")
        file_handler = logging.FileHandler(self.human_log_path, encoding="utf-8")
        file_handler.setFormatter(fmt)
        self.logger.addHandler(file_handler)

        console_handler = logging.StreamHandler(sys.stdout)
        console_handler.setFormatter(fmt)
        self.logger.addHandler(console_handler)

    def info(self, message: str, **data: Any) -> None:
        self._write("INFO", message, data)

    def warning(self, message: str, **data: Any) -> None:
        self._write("WARNING", message, data)

    def error(self, message: str, **data: Any) -> None:
        self._write("ERROR", message, data)

    def check(self, name: str, passed: bool, **data: Any) -> None:
        self._write("INFO" if passed else "WARNING", f"CHECK {name}: {'PASS' if passed else 'FAIL'}", {
            "check": name,
            "passed": passed,
            **data,
        })

    def http(self, method: str, url: str, payload: Any, response: requests.Response | None, body: Any, label: str, retry: bool = False) -> None:
        status_code = response.status_code if response is not None else None
        ok = bool(response.ok) if response is not None else False
        self._write("INFO" if ok else "WARNING", f"HTTP {method} {url} -> {status_code} | {label}", {
            "event": "http_request",
            "label": label,
            "method": method,
            "url": url,
            "request_payload": redact(payload),
            "status_code": status_code,
            "ok": ok,
            "response_body": redact(body),
            "retry": retry,
        })

    def _write(self, level: str, message: str, data: dict[str, Any]) -> None:
        record = {
            "ts_utc": now_utc_iso(),
            "level": level,
            "message": message,
            **redact(data),
        }
        with self.jsonl_log_path.open("a", encoding="utf-8") as f:
            f.write(json.dumps(record, ensure_ascii=False, default=str) + "\n")

        suffix = " | " + json.dumps(redact(data), ensure_ascii=False, default=str) if data else ""
        if level == "ERROR":
            self.logger.error(message + suffix)
        elif level == "WARNING":
            self.logger.warning(message + suffix)
        else:
            self.logger.info(message + suffix)


# =============================================================================
# API CLIENT
# =============================================================================

def parse_response_body(response: requests.Response) -> Any:
    try:
        return response.json()
    except Exception:
        return response.text


class EVClient:
    def __init__(self, base_url: str, logger: StructuredLogger, username: str | None = None, password: str | None = None):
        self.base_url = base_url.rstrip("/")
        self.logger = logger
        self.username = username
        self.password = password
        self.token: str | None = None
        self.owner_id: str | None = None

    @property
    def auth_headers(self) -> dict[str, str]:
        return {"Authorization": f"Bearer {self.token}"} if self.token else {}

    def login(self, username: str | None = None, password: str | None = None) -> dict[str, Any]:
        if username is not None:
            self.username = username
        if password is not None:
            self.password = password
        if not self.username or not self.password:
            raise RuntimeError("Missing username/password for login.")

        body = self.request(
            "POST",
            "/auth/login",
            json_payload={"user": self.username, "password": self.password},
            auth=False,
            label=f"login {self.username}",
            retry_on_401=False,
        )
        if not isinstance(body, dict) or "access_token" not in body:
            raise RuntimeError(f"Login did not return an access_token. Response: {body}")
        self.token = str(body["access_token"])
        self.owner_id = str(body.get("owner_id")) if body.get("owner_id") is not None else None
        self.logger.info("Logged in", username=self.username, owner_id=self.owner_id)
        return body

    def logout(self) -> None:
        if not self.token:
            return
        try:
            self.try_request("POST", "/auth/logout", label=f"logout {self.username}", retry_on_401=False)
        finally:
            self.token = None
            self.owner_id = None
            self.logger.info("Local token cleared", username=self.username)

    def request(
        self,
        method: str,
        path: str,
        *,
        json_payload: Any | None = None,
        params: dict[str, Any] | None = None,
        auth: bool = True,
        label: str = "",
        retry_on_401: bool = True,
    ) -> Any:
        url = f"{self.base_url}{path}"
        payload_for_log = json_payload if json_payload is not None else params
        response: requests.Response | None = None
        body: Any = None

        response = requests.request(
            method,
            url,
            headers=self.auth_headers if auth else {},
            json=json_payload,
            params=params,
            timeout=HTTP_TIMEOUT_SECONDS,
        )
        body = parse_response_body(response)
        self.logger.http(method, url, payload_for_log, response, body, label)

        if response.status_code == 401 and auth and retry_on_401 and self.username and self.password:
            self.logger.warning("401 received; token may have expired. Re-authenticating and retrying once.", path=path)
            self.login(self.username, self.password)
            response = requests.request(
                method,
                url,
                headers=self.auth_headers,
                json=json_payload,
                params=params,
                timeout=HTTP_TIMEOUT_SECONDS,
            )
            body = parse_response_body(response)
            self.logger.http(method, url, payload_for_log, response, body, label, retry=True)

        response.raise_for_status()
        return body

    def try_request(
        self,
        method: str,
        path: str,
        *,
        json_payload: Any | None = None,
        params: dict[str, Any] | None = None,
        auth: bool = True,
        label: str = "",
        retry_on_401: bool = True,
    ) -> tuple[bool, Any]:
        try:
            body = self.request(
                method,
                path,
                json_payload=json_payload,
                params=params,
                auth=auth,
                label=label,
                retry_on_401=retry_on_401,
            )
            return True, body
        except Exception as exc:
            self.logger.warning("Non-fatal request failed", method=method, path=path, label=label, error=str(exc))
            return False, str(exc)


# =============================================================================
# DATA MODELS AND CSV HELPERS
# =============================================================================

@dataclass
class Charger:
    id: str
    name: str
    nominal_power_kw: float


@dataclass
class ScheduleEvent:
    row_id: int
    synthetic_session_id: str
    day_index: int
    charger_index: int
    charger_name: str
    charger_id: str
    event_type: str
    timestamp_delta_minutes: int
    start_delta_minutes: int
    end_delta_minutes: int
    end_charging_delta_minutes: int
    charging_rate_kw: float
    energy_since_last_event_kwh: float
    cumulative_energy_kwh: float
    fully_charged: bool
    action: int
    nominal_power_kw: float
    target_energy_kwh: float
    expected_duration_minutes: int


def parse_bool(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in {"true", "1", "yes", "y"}


def parse_event(row: dict[str, str]) -> ScheduleEvent:
    return ScheduleEvent(
        row_id=int(row["row_id"]),
        synthetic_session_id=row["synthetic_session_id"],
        day_index=int(row["day_index"]),
        charger_index=int(row["charger_index"]),
        charger_name=row["charger_name"],
        charger_id=row.get("charger_id", ""),
        event_type=row["event_type"],
        timestamp_delta_minutes=int(float(row["timestamp_delta_minutes"])),
        start_delta_minutes=int(float(row["start_delta_minutes"])),
        end_delta_minutes=int(float(row["end_delta_minutes"])),
        end_charging_delta_minutes=int(float(row["end_charging_delta_minutes"])),
        charging_rate_kw=float(row["charging_rate_kw"]),
        energy_since_last_event_kwh=float(row["energy_since_last_event_kwh"]),
        cumulative_energy_kwh=float(row["cumulative_energy_kwh"]),
        fully_charged=parse_bool(row["fully_charged"]),
        action=int(float(row["action"])),
        nominal_power_kw=float(row["nominal_power_kw"]),
        target_energy_kwh=float(row["target_energy_kwh"]),
        expected_duration_minutes=int(float(row["expected_duration_minutes"])),
    )


def load_schedule(path: Path) -> list[ScheduleEvent]:
    if not path.exists():
        raise FileNotFoundError(
            f"Schedule CSV not found: {path}. Run generate_charging_schedule.py first."
        )
    with path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        events = [parse_event(row) for row in reader]
    events.sort(key=lambda event: (event.timestamp_delta_minutes, event.row_id))
    return events


def write_resolved_schedule(path: Path, events: list[ScheduleEvent], reference_start: datetime) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    rows = []
    for event in events:
        row = asdict(event)
        row["timestamp_abs"] = timestamp_from_delta(reference_start, event.timestamp_delta_minutes)
        row["start_abs"] = timestamp_from_delta(reference_start, event.start_delta_minutes)
        row["end_abs"] = timestamp_from_delta(reference_start, event.end_delta_minutes)
        row["end_charging_abs"] = timestamp_from_delta(reference_start, event.end_charging_delta_minutes)
        rows.append(row)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def timestamp_from_delta(reference_start: datetime, delta_minutes: int) -> str:
    return (reference_start + timedelta(minutes=delta_minutes)).isoformat()


# =============================================================================
# ID AND OBJECT HELPERS
# =============================================================================

def as_list(body: Any) -> list[Any]:
    if isinstance(body, list):
        return body
    if isinstance(body, dict):
        for key in ("items", "data", "results", "owners", "pilots", "chargers"):
            if isinstance(body.get(key), list):
                return body[key]
    return []


def get_id(obj: dict[str, Any]) -> str | None:
    for key in ("id", "owner_id", "id_owner", "pilot_id", "id_pilot", "charger_id", "id_charger"):
        if obj.get(key) is not None:
            return str(obj[key])
    return None


def find_by_user(rows: Iterable[Any], user: str) -> dict[str, Any] | None:
    for row in rows:
        if isinstance(row, dict) and row.get("user") == user:
            return row
    return None


def find_by_name(rows: Iterable[Any], name: str) -> dict[str, Any] | None:
    for row in rows:
        if isinstance(row, dict) and row.get("name") == name:
            return row
    return None


def charger_name(index: int) -> str:
    return f"{PILOT_NAME} CP{index}"


# =============================================================================
# IDEMPOTENT SETUP
# =============================================================================

def get_or_create_owner(admin: EVClient) -> dict[str, Any]:
    owners = as_list(admin.request("GET", "/db/owners", label="list owners before creating test user"))
    existing = find_by_user(owners, TEST_USERNAME)
    if existing:
        admin.logger.info("Reusing existing owner", user=TEST_USERNAME, owner_id=get_id(existing))
        return existing

    payload = {
        "user": TEST_USERNAME,
        "password": TEST_PASSWORD,
        "company_name": TEST_COMPANY_NAME,
        "role": TEST_USER_ROLE,
        "type": TEST_USER_TYPE,
    }
    ok, body = admin.try_request("POST", "/db/owners", json_payload=payload, label="create test owner")
    if ok and isinstance(body, dict):
        return body

    # If the API replied with a duplicate error, fetch the owner again.
    owners = as_list(admin.request("GET", "/db/owners", label="list owners after create-owner fallback"))
    existing = find_by_user(owners, TEST_USERNAME)
    if existing:
        admin.logger.info("Owner exists after create-owner fallback", user=TEST_USERNAME, owner_id=get_id(existing))
        return existing
    raise RuntimeError(f"Could not create or find owner {TEST_USERNAME}. Last response: {body}")


def get_or_create_pilot(admin: EVClient, owner_id: str) -> dict[str, Any]:
    pilots = as_list(admin.request("GET", "/db/pilots", label="list pilots before creating test pilot"))
    existing = find_by_name(pilots, PILOT_NAME)
    if existing:
        admin.logger.info("Reusing existing pilot", pilot=PILOT_NAME, pilot_id=get_id(existing))
        return existing

    payload = {
        "name": PILOT_NAME,
        "id_owner": owner_id,
        "timezone_name": PILOT_TIMEZONE,
    }
    ok, body = admin.try_request("POST", "/db/pilots", json_payload=payload, label="create test pilot")
    if ok and isinstance(body, dict):
        return body

    pilots = as_list(admin.request("GET", "/db/pilots", label="list pilots after create-pilot fallback"))
    existing = find_by_name(pilots, PILOT_NAME)
    if existing:
        admin.logger.info("Pilot exists after create-pilot fallback", pilot=PILOT_NAME, pilot_id=get_id(existing))
        return existing
    raise RuntimeError(f"Could not create or find pilot {PILOT_NAME}. Last response: {body}")


def get_or_create_chargers(client: EVClient, owner_id: str, pilot_id: str) -> list[Charger]:
    chargers_body = as_list(client.request("GET", "/db/chargers", label="list chargers before creation/reuse"))
    existing_by_name = {row.get("name"): row for row in chargers_body if isinstance(row, dict)}

    chargers: list[Charger] = []
    for index in range(1, CHARGER_COUNT + 1):
        name = charger_name(index)
        existing = existing_by_name.get(name)
        if existing:
            cid = get_id(existing)
            if not cid:
                raise RuntimeError(f"Existing charger has no ID: {existing}")
            nominal = float(existing.get("nominal_power", existing.get("nominal_power_kw", NOMINAL_POWER_KW)))
            chargers.append(Charger(id=cid, name=name, nominal_power_kw=nominal))
            client.logger.info("Reusing existing charger", charger=name, charger_id=cid)
            continue

        payload = {
            "name": name,
            "type": CHARGER_TYPE,
            "latitude": round(BASE_LATITUDE + index * 0.004, 3),
            "longitude": round(BASE_LONGITUDE + index * 0.004, 3),
            "nominal_power": NOMINAL_POWER_KW,
            "plugs": PLUGS,
            "id_owner": owner_id,
            "id_pilot": pilot_id,
        }
        ok, body = client.try_request("POST", "/db/chargers", json_payload=payload, label=f"create charger {name}")
        if ok and isinstance(body, dict):
            cid = get_id(body)
            if not cid:
                raise RuntimeError(f"Created charger response has no ID: {body}")
            chargers.append(Charger(id=cid, name=name, nominal_power_kw=NOMINAL_POWER_KW))
            continue

        # Fallback after duplicate or permission-like issue.
        chargers_body = as_list(client.request("GET", "/db/chargers", label="list chargers after charger-create fallback"))
        existing = find_by_name(chargers_body, name)
        if existing:
            cid = get_id(existing)
            if not cid:
                raise RuntimeError(f"Existing charger has no ID: {existing}")
            nominal = float(existing.get("nominal_power", existing.get("nominal_power_kw", NOMINAL_POWER_KW)))
            chargers.append(Charger(id=cid, name=name, nominal_power_kw=nominal))
            continue
        raise RuntimeError(f"Could not create or find charger {name}. Last response: {body}")

    return chargers


def inject_charger_ids(events: list[ScheduleEvent], chargers: list[Charger]) -> None:
    by_name = {charger.name: charger for charger in chargers}
    for event in events:
        charger = by_name.get(event.charger_name)
        if not charger:
            raise RuntimeError(f"Schedule references unknown charger name: {event.charger_name}")
        event.charger_id = charger.id


# =============================================================================
# EVENT EXECUTION AND VALIDATION
# =============================================================================

def event_payload(event: ScheduleEvent, reference_start: datetime) -> dict[str, Any]:
    timestamp = timestamp_from_delta(reference_start, event.timestamp_delta_minutes)
    if event.event_type == "vehicle_connected":
        return {
            "charger_id": event.charger_id,
            "timestamp": timestamp,
            "measured_power_kw": event.charging_rate_kw,
            "is_fully_charged": event.fully_charged,
        }
    if event.event_type == "charging_update":
        return {
            "charger_id": event.charger_id,
            "timestamp": timestamp,
            "avg_power_last_15min_kw": event.charging_rate_kw,
            "energy_delivered_kwh": event.energy_since_last_event_kwh,
            "is_fully_charged": event.fully_charged,
        }
    if event.event_type == "vehicle_disconnected":
        return {
            "charger_id": event.charger_id,
            "timestamp": timestamp,
            "avg_power_last_15min_kw": event.charging_rate_kw,
            "energy_delivered_kwh": event.energy_since_last_event_kwh,
            "is_fully_charged": event.fully_charged,
        }
    raise ValueError(f"Unsupported event_type: {event.event_type}")


def extract_session_id(body: Any) -> str | None:
    if isinstance(body, dict):
        for key in ("session_id", "id_session", "id", "sessionId"):
            if body.get(key) is not None:
                return str(body[key])
        for value in body.values():
            found = extract_session_id(value)
            if found:
                return found
    if isinstance(body, list):
        for item in body:
            found = extract_session_id(item)
            if found:
                return found
    return None


def active_count_from_body(body: Any) -> int | None:
    if isinstance(body, dict):
        for key in ("count", "active_count", "n_active", "total"):
            if key in body:
                try:
                    return int(body[key])
                except Exception:
                    pass
        for key in ("items", "data", "results", "sessions", "active_sessions"):
            if isinstance(body.get(key), list):
                return len(body[key])
        # In the debug script, active sessions are treated as a dict keyed by session ID.
        return len(body)
    if isinstance(body, list):
        return len(body)
    return None


def resolve_session_id_from_active_sessions(body: Any, charger_id: str) -> str | None:
    if isinstance(body, dict):
        for possible_session_id, value in body.items():
            if isinstance(value, dict):
                if str(value.get("charger_id") or value.get("id_charger") or "") == str(charger_id):
                    return str(possible_session_id)
                found = extract_session_id(value)
                if found and str(value.get("charger_id") or value.get("id_charger") or "") == str(charger_id):
                    return found
        for key in ("items", "data", "results", "sessions", "active_sessions"):
            if isinstance(body.get(key), list):
                return resolve_session_id_from_active_sessions(body[key], charger_id)
    elif isinstance(body, list):
        for row in body:
            if isinstance(row, dict) and str(row.get("charger_id") or row.get("id_charger") or "") == str(charger_id):
                return extract_session_id(row)
    return None


def active_validation_deltas() -> list[int]:
    step = int(24 * 60 / ACTIVE_SESSION_CHECKS_PER_DAY)
    deltas: list[int] = []
    for day in range(SCHEDULE_DAYS):
        day_offset = day * 24 * 60
        for i in range(ACTIVE_SESSION_CHECKS_PER_DAY):
            # Add 15 minutes to avoid checking exactly at midnight / boundary points.
            deltas.append(day_offset + i * step + 15)
    return deltas


def expected_active_session_ids(events: list[ScheduleEvent], delta_minutes: int) -> list[str]:
    by_session: dict[str, tuple[int, int]] = {}
    for event in events:
        by_session[event.synthetic_session_id] = (event.start_delta_minutes, event.end_delta_minutes)
    return [session_id for session_id, (start, end) in by_session.items() if start <= delta_minutes < end]


def sleep_until_next_delta(previous_delta: int, next_delta: int, logger: StructuredLogger) -> None:
    if not USE_SLEEP_BETWEEN_SCHEDULED_CALLS:
        return
    delta = max(0, next_delta - previous_delta)
    sleep_seconds = delta * 60.0 / TIME_SCALE
    if sleep_seconds > 0:
        logger.info("Sleeping before next scheduled API call", simulated_delta_minutes=delta, sleep_seconds=round(sleep_seconds, 3))
        time.sleep(sleep_seconds)


def execute_schedule(client: EVClient, events: list[ScheduleEvent], reference_start: datetime) -> str | None:
    events_by_delta: dict[int, list[ScheduleEvent]] = defaultdict(list)
    for event in events:
        events_by_delta[event.timestamp_delta_minutes].append(event)

    checkpoints = set(active_validation_deltas())
    timeline = sorted(set(events_by_delta.keys()) | checkpoints)
    previous_delta = 0
    known_api_session_ids: dict[str, str] = {}
    last_synthetic_session_id = events[-1].synthetic_session_id if events else None
    last_api_session_id: str | None = None

    for delta in timeline:
        sleep_until_next_delta(previous_delta, delta, client.logger)
        previous_delta = delta

        for event in events_by_delta.get(delta, []):
            if event.event_type == "vehicle_disconnected":
                # Try to capture API session ID just before closing the session.
                ok, active_body = client.try_request("GET", "/events/active_sessions", label="active sessions before disconnect")
                if ok:
                    sid = resolve_session_id_from_active_sessions(active_body, event.charger_id)
                    if sid:
                        known_api_session_ids[event.synthetic_session_id] = sid
                        if event.synthetic_session_id == last_synthetic_session_id:
                            last_api_session_id = sid

            path = f"/events/{event.event_type}"
            payload = event_payload(event, reference_start)
            ok, body = client.try_request("POST", path, json_payload=payload, label=f"{event.event_type} {event.synthetic_session_id}")
            if not ok:
                client.logger.warning("Charging event failed", event=asdict(event), response=body)
                continue

            sid = extract_session_id(body)
            if sid:
                known_api_session_ids[event.synthetic_session_id] = sid
                if event.synthetic_session_id == last_synthetic_session_id:
                    last_api_session_id = sid

        if delta in checkpoints:
            expected_ids = expected_active_session_ids(events, delta)
            ok, active_body = client.try_request("GET", "/events/active_sessions", label="scheduled active-session validation")
            actual_count = active_count_from_body(active_body) if ok else None
            client.logger.check(
                "active_sessions_count",
                passed=ok and actual_count == len(expected_ids),
                timestamp_delta_minutes=delta,
                timestamp_abs=timestamp_from_delta(reference_start, delta),
                expected_active_sessions=len(expected_ids),
                actual_active_sessions=actual_count,
                expected_synthetic_session_ids=expected_ids,
                details=active_body,
            )

    if last_api_session_id is None and last_synthetic_session_id is not None:
        last_api_session_id = known_api_session_ids.get(last_synthetic_session_id)
    return last_api_session_id


# =============================================================================
# FORECAST VALIDATION
# =============================================================================

def session_rows(events: list[ScheduleEvent]) -> dict[str, list[ScheduleEvent]]:
    grouped: dict[str, list[ScheduleEvent]] = defaultdict(list)
    for event in events:
        grouped[event.synthetic_session_id].append(event)
    return grouped


def schedule_hourly_stats(events: list[ScheduleEvent], reference_start: datetime, charger_id: str | None = None) -> dict[int, dict[str, float]]:
    grouped_sessions = session_rows(events)
    by_hour: dict[int, list[dict[str, float]]] = defaultdict(list)

    for rows in grouped_sessions.values():
        first = rows[0]
        if charger_id is not None and str(first.charger_id) != str(charger_id):
            continue
        start_hour = (reference_start + timedelta(minutes=first.start_delta_minutes)).hour
        total_energy = sum(row.energy_since_last_event_kwh for row in rows)
        duration_h = (first.end_delta_minutes - first.start_delta_minutes) / 60.0
        by_hour[start_hour].append({"energy": total_energy, "duration": duration_h})

    stats = {}
    for hour, values in by_hour.items():
        stats[hour] = {
            "mean_energy_kwh": sum(v["energy"] for v in values) / len(values),
            "mean_duration_hours": sum(v["duration"] for v in values) / len(values),
            "sample_count": len(values),
        }
    return stats


def first_float(row: dict[str, Any], keys: list[str]) -> float | None:
    for key in keys:
        if key in row and row[key] is not None:
            try:
                return float(row[key])
            except Exception:
                return None
    return None


def normalise_latest_forecast(body: Any) -> list[dict[str, Any]]:
    if isinstance(body, list):
        raw_rows = body
    elif isinstance(body, dict):
        raw_rows = []
        for key in ("items", "data", "results", "forecast", "forecasts", "rows"):
            if isinstance(body.get(key), list):
                raw_rows = body[key]
                break
        if not raw_rows:
            raw_rows = [body]
    else:
        raw_rows = []

    normalised: list[dict[str, Any]] = []
    for row in raw_rows:
        if not isinstance(row, dict):
            continue
        hour = row.get("local_hour", row.get("hour", row.get("starting_hour")))
        if hour is None:
            ts = row.get("timestamp") or row.get("start_time") or row.get("datetime")
            if ts:
                try:
                    hour = datetime.fromisoformat(str(ts).replace("Z", "+00:00")).hour
                except Exception:
                    hour = None
        try:
            hour = int(hour) if hour is not None else None
        except Exception:
            hour = None
        if hour is None:
            continue

        normalised.append({
            "hour": hour,
            "source": row.get("source", row.get("forecast_source", "charger")),
            "mean_energy_kwh": first_float(row, ["mean_energy_kwh", "energy_kWh", "energy_kwh", "mean_energy", "energy"]),
            "mean_duration_hours": first_float(row, ["mean_duration_hours", "duration_hours", "mean_duration", "duration"]),
            "raw": row,
        })
    return normalised


def validate_latest_forecast(client: EVClient, latest_body: Any, events: list[ScheduleEvent], reference_start: datetime, reference_charger_id: str) -> None:
    charger_stats = schedule_hourly_stats(events, reference_start, charger_id=reference_charger_id)
    global_stats = schedule_hourly_stats(events, reference_start, charger_id=None)
    rows = normalise_latest_forecast(latest_body)

    if not rows:
        client.logger.warning("Could not normalise latest forecast response; skipping detailed comparison", response=latest_body)
        return

    for row in rows:
        hour = row["hour"]
        source = str(row.get("source") or "charger").lower()
        expected = global_stats.get(hour) if source == "generic" else charger_stats.get(hour)
        reference = charger_stats.get(hour)
        global_hour = global_stats.get(hour)

        if expected is None:
            client.logger.warning(
                "No schedule-derived statistics for forecast hour",
                hour=hour,
                source=source,
                api_row=row["raw"],
                expected_reference_value=reference,
                expected_global_value=global_hour,
            )
            continue

        for metric in ("mean_energy_kwh", "mean_duration_hours"):
            api_value = row.get(metric)
            expected_value = expected.get(metric)
            if api_value is None or expected_value is None:
                client.logger.warning("Missing forecast metric", hour=hour, source=source, metric=metric, api_row=row["raw"])
                continue
            difference = api_value - expected_value
            passed = math.isclose(api_value, expected_value, abs_tol=FORECAST_COMPARISON_ABS_TOLERANCE)
            client.logger.check(
                f"latest_forecast_{metric}",
                passed=passed,
                hour=hour,
                source=source,
                metric=metric,
                api_value=api_value,
                expected_reference_value=reference.get(metric) if reference else None,
                expected_global_value=global_hour.get(metric) if global_hour else None,
                selected_expected_value=expected_value,
                difference=difference,
                validation_status="pass" if passed else "difference_exceeds_tolerance",
            )


# =============================================================================
# SANITY CHECKS
# =============================================================================

def validate_schedule_file(events: list[ScheduleEvent], logger: StructuredLogger) -> None:
    if not events:
        raise RuntimeError("The schedule CSV contains no events.")

    zero_bad = [e for e in events if e.action == 0 and (e.energy_since_last_event_kwh != 0 or e.charging_rate_kw != 0)]
    logger.check(
        "action_zero_has_zero_power_and_energy",
        passed=len(zero_bad) == 0,
        invalid_rows=[e.row_id for e in zero_bad[:20]],
        invalid_count=len(zero_bad),
    )

    too_high_power = [e for e in events if e.charging_rate_kw >= e.nominal_power_kw]
    logger.check(
        "charging_rate_below_nominal_power",
        passed=len(too_high_power) == 0,
        invalid_rows=[e.row_id for e in too_high_power[:20]],
        invalid_count=len(too_high_power),
    )

    zero_not_full_total = 0
    zero_not_full_by_charger: dict[str, int] = defaultdict(int)
    for event in events:
        if event.action == 0 and not event.fully_charged:
            zero_not_full_total += 1
            zero_not_full_by_charger[event.charger_name] += 1
    logger.info(
        "Counted action=0 while vehicle not fully charged",
        total=zero_not_full_total,
        by_charger=dict(zero_not_full_by_charger),
    )


def verify_admin_credentials_are_not_placeholders() -> None:
    if "PLACEHOLDER" in ADMIN_USERNAME or "PLACEHOLDER" in ADMIN_PASSWORD:
        raise RuntimeError(
            "Please edit ADMIN_USERNAME and ADMIN_PASSWORD at the top of run_e2e_api_test.py before running."
        )


# =============================================================================
# MAIN WORKFLOW
# =============================================================================

def main() -> None:
    verify_admin_credentials_are_not_placeholders()

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    tz = ZoneInfo(TIMEZONE)
    run_id = datetime.now(tz).strftime("%Y%m%d_%H%M%S")
    logger = StructuredLogger(OUTPUT_DIR, run_id)

    logger.info("Starting EV Orchestrator E2E API test", base_url=BASE_URL, schedule_csv=str(SCHEDULE_CSV_PATH), run_id=run_id)

    # 0. Health check / reachability.
    public_client = EVClient(BASE_URL, logger)
    ok, health_body = public_client.try_request("GET", "/health", auth=False, label="health check /health")
    if not ok:
        ok_docs, docs_body = public_client.try_request("GET", "/docs", auth=False, label="fallback reachability check /docs")
        logger.check("service_reachable", passed=ok_docs, health_response=health_body, docs_response=docs_body)
    else:
        logger.check("service_reachable", passed=True, health_response=health_body)

    # Load and check CSV before writing anything to the API.
    events = load_schedule(SCHEDULE_CSV_PATH)
    validate_schedule_file(events, logger)

    # 1. Login as admin.
    admin = EVClient(BASE_URL, logger, ADMIN_USERNAME, ADMIN_PASSWORD)
    admin.login()

    # 2. Create/reuse user.
    owner = get_or_create_owner(admin)
    owner_id = get_id(owner)
    if not owner_id:
        raise RuntimeError(f"Cannot determine owner id for {TEST_USERNAME}: {owner}")

    # 3. Create/reuse pilot.
    pilot = get_or_create_pilot(admin, owner_id)
    pilot_id = get_id(pilot)
    if not pilot_id:
        raise RuntimeError(f"Cannot determine pilot id for {PILOT_NAME}: {pilot}")

    # 4. Logout admin.
    admin.logout()

    # 5. Login as interped_user1.
    user_client = EVClient(BASE_URL, logger, TEST_USERNAME, TEST_PASSWORD)
    user_client.login()

    # 6. Check existing pilots.
    pilots = as_list(user_client.request("GET", "/db/pilots", label="list pilots as interped_user1"))
    pilot_visible = find_by_name(pilots, PILOT_NAME) is not None
    logger.check("pilot_visible_to_interped_user1", passed=pilot_visible, pilot_name=PILOT_NAME)

    # 7. Create/reuse chargers. If user permissions do not allow this, retry as admin.
    try:
        chargers = get_or_create_chargers(user_client, owner_id, pilot_id)
    except Exception as exc:
        logger.warning("Charger setup as interped_user1 failed; retrying as admin", error=str(exc))
        user_client.logout()
        admin = EVClient(BASE_URL, logger, ADMIN_USERNAME, ADMIN_PASSWORD)
        admin.login()
        chargers = get_or_create_chargers(admin, owner_id, pilot_id)
        admin.logout()
        user_client.login()

    if len(chargers) != CHARGER_COUNT:
        raise RuntimeError(f"Expected {CHARGER_COUNT} chargers; got {len(chargers)}")

    # Resolve charger IDs into the schedule and log the runtime reference start.
    inject_charger_ids(events, chargers)
    reference_start = datetime.now(tz).replace(second=0, microsecond=0) + timedelta(minutes=START_DELAY_MINUTES)
    resolved_schedule_path = OUTPUT_DIR / f"{RESOLVED_SCHEDULE_PREFIX}_{run_id}.csv"
    write_resolved_schedule(resolved_schedule_path, events, reference_start)
    logger.info(
        "Resolved schedule and reference start",
        reference_start=reference_start.isoformat(),
        resolved_schedule_csv=str(resolved_schedule_path),
        time_scale=TIME_SCALE,
        use_sleep_between_scheduled_calls=USE_SLEEP_BETWEEN_SCHEDULED_CALLS,
    )

    if DRY_RUN_AFTER_SETUP:
        logger.warning("DRY_RUN_AFTER_SETUP is True; stopping before session event execution")
        user_client.logout()
        print_output_summary(logger, resolved_schedule_path)
        return

    # 8 and 9. Execute synthetic schedule and validate active sessions 4 times/day.
    last_api_session_id = execute_schedule(user_client, events, reference_start)

    # Additional one-off endpoint checks.
    for path in ("/db/owners", "/db/pilots", "/db/chargers"):
        user_client.try_request("GET", path, label=f"one-off endpoint check {path}")

    # 10. Charger history for one charger.
    history_charger = chargers[0]
    user_client.try_request("GET", f"/forecaster/charger/{history_charger.id}/history", label=f"charger history {history_charger.name}")

    # 11. Latest charger forecast for another charger + comparison.
    latest_charger = chargers[1]
    ok, latest_body = user_client.try_request("GET", f"/forecaster/charger/{latest_charger.id}/latest", label=f"charger latest {latest_charger.name}")
    if ok:
        validate_latest_forecast(user_client, latest_body, events, reference_start, reference_charger_id=latest_charger.id)

    # 12. Actions for last session.
    if last_api_session_id:
        ok, actions_body = user_client.try_request("GET", f"/sessions/actions/session/{last_api_session_id}", label="last session actions")
        if ok:
            print("\n/sessions/actions/session/{session_id} response for the last session:")
            print(json.dumps(actions_body, indent=2, default=str))
    else:
        logger.warning("Could not determine API session ID for the last synthetic session; skipping session actions endpoint")

    # 13. Forecast jobs.
    ok, forecast_jobs_body = user_client.try_request("GET", "/db/forecast_jobs", label="list forecast jobs")
    if ok:
        print("\n/db/forecast_jobs response:")
        print(json.dumps(forecast_jobs_body, indent=2, default=str))

    # 14. Logout.
    user_client.logout()

    logger.info("Completed EV Orchestrator E2E API test")
    print_output_summary(logger, resolved_schedule_path)


def print_output_summary(logger: StructuredLogger, resolved_schedule_path: Path) -> None:
    print("\nGenerated / updated files:")
    print(f"  human log:          {logger.human_log_path}")
    print(f"  structured JSONL:   {logger.jsonl_log_path}")
    print(f"  resolved schedule:  {resolved_schedule_path}")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\nInterrupted by user.", file=sys.stderr)
        sys.exit(130)
    except requests.exceptions.ConnectionError as exc:
        print(f"\nERROR: Cannot connect to {BASE_URL}. Details: {exc}", file=sys.stderr)
        sys.exit(1)
    except Exception as exc:
        print(f"\nERROR: {exc}", file=sys.stderr)
        sys.exit(1)
